/* STATE VARIABLES */
export const SET_STATE_VARIABLE = "SET_STATE_VARIABLE";

/* CURRENT SEARCH */
export const GET_CURRENT_SEARCH_DATA = "GET_CURRENT_SEARCH_DATA";
export const SET_CURRENT_SEARCH_DATA = "SET_CURRENT_SEARCH_DATA";

/* CURRENT MOVIE */
export const GET_CURRENT_MOVIE_DATA = "GET_CURRENT_MOVIE_DATA";
export const SET_CURRENT_MOVIE_DATA = "SET_CURRENT_MOVIE_DATA";

/* HOMEPAGE */
export const GET_MOVIES = "GET_MOVIES";
export const SET_MOVIES = "SET_MOVIES";
