/* STATE VARIABLES */
export const SET_STATE_VARIABLE = "SET_STATE_VARIABLE";

/* CURRENT SEARCH */
export const GET_CURRENT_SEARCH_DATA = "GET_CURRENT_SEARCH_DATA";
export const SET_CURRENT_SEARCH_DATA = "SET_CURRENT_SEARCH_DATA";

/* CURRENT MOVIE */
export const GET_CURRENT_MOVIE_DATA = "GET_CURRENT_MOVIE_DATA";
export const SET_CURRENT_MOVIE_DATA = "SET_CURRENT_MOVIE_DATA";

/* HOMEPAGE */
export const GET_MOVIES = "GET_MOVIES";
export const SET_MOVIES = "SET_MOVIES";

/* USER */
export const AUTHORISE_USER = "AUTHORISE_USER";
export const LOGOUT = "LOGOUT";
export const GET_CURRENT_USER_DATA = "GET_CURRENT_USER_DATA";
export const SET_CURRENT_USER_DATA = "SET_CURRENT_USER_DATA";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const ADD_TO_WATCHLIST = "ADD_TO_WATCHLIST";
export const REMOVE_FROM_WATCHLIST = "REMOVE_FROM_WATCHLIST";
